package h5

var (
	// Scopes
	allScope  = map[string]bool{}
	baseScope = map[string]bool{
		"applet":         true,
		"caption":        true,
		"html":           true,
		"table":          true,
		"td":             true,
		"th":             true,
		"marquee":        true,
		"object":         true,
		"mi":             true,
		"mo":             true,
		"mn":             true,
		"ms":             true,
		"mtext":          true,
		"annotation-xml": true,
		"foreignObject":  true,
		"desc":           true,
		"title":          true,
	}
	buttonScope = map[string]bool{
		"applet":         true,
		"caption":        true,
		"html":           true,
		"table":          true,
		"td":             true,
		"th":             true,
		"marquee":        true,
		"object":         true,
		"mi":             true,
		"mo":             true,
		"mn":             true,
		"ms":             true,
		"mtext":          true,
		"annotation-xml": true,
		"foreignObject":  true,
		"desc":           true,
		"title":          true,
		"button":         true,
	}
	listScope = map[string]bool{
		"applet":         true,
		"caption":        true,
		"html":           true,
		"table":          true,
		"td":             true,
		"th":             true,
		"marquee":        true,
		"object":         true,
		"mi":             true,
		"mo":             true,
		"mn":             true,
		"ms":             true,
		"mtext":          true,
		"annotation-xml": true,
		"foreignObject":  true,
		"desc":           true,
		"title":          true,
		"ol":             true,
		"ul":             true,
	}
)
